version: '2'

services:
    rasa-trainer:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        restart: unless-stopped
        ports: 
            - 8080:8080
        volumes:
            - ./app:/rasa-nlu-trainer
