version: "3.4"

services:
  # ============================ Rasa-nlu-trainer =============================
  rasa-trainer:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: react
    restart: unless-stopped
    depends_on:
      - mongo
# ============================ Mongo ==========================================
  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --oplogSize 128
    ports:
      - 27017:27017
  # ============================ Node ==========================================
  node-server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: node
    restart: unless-stopped
    ports:
      - 3030:3030
    volumes:
      - ./node_server/:/node_server/
      - /node_server/node_modules
