version: "2"

services:
  rasa-trainer:
    build:
      context: .
      dockerfile: ./docker/react.Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
      - 3000:3000
    volumes:
      - ./app:/rasa-nlu-trainer
    command: npm start
  node-server:
    build:
      context: .
      dockerfile: ./docker/nodeServer.Dockerfile
    restart: unless-stopped
    ports:
      - 4321:4321
    volumes:
      - ./node_server:/node_server
    command: node server.js -p 4321 -d true &!
