version: "3.4"

services:
 rasa-trainer:
   build:
     context: .
     dockerfile: ./docker/Dockerfile
     target: react
   restart: unless-stopped
   ports:
     - 8080:8080
     - 3000:3000
   volumes:
     - ./app/src:/rasa-nlu-trainer/src
   command: npm start

