version: "3.4"

services:
  rasa-trainer:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: react
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./app/:/rasa-nlu-trainer/
      - /app/node_modules

    
